### ISSUE TITLE
Calling an added event results causes the index of 0 to not be found.

### ISSUE THREAD

**Issue by gsBASE** [samisalreadytaken/vs_library#13]
This seems to be caused when any one of the following consecutivley added events are called:

```
// Three attacks and one to return to idle
VS.EventQueue.AddEvent( Phase2Attack, 0.0, [this, 3] );
VS.EventQueue.AddEvent( Phase2Attack, 3.1, [this, 3] );
VS.EventQueue.AddEvent( Phase2Attack, 6.2, [this, 3] );
VS.EventQueue.AddEvent(ChangeStateToIdle, 9.3);
```

Occasionally, the entire event system will fail with the error that the index of 0 does not exist at line 6 of vs_library.nut

This seems to happen when the event is called, not when it is added, and it does not seem to happen consistently on any hardware.

**Comment by samisalreadytaken** [comment]
Does it happen in the middle of a round, or only at the end of one? Events can't be carried across rounds because game's event queue is cleared by the game at the start of every round; this wouldn't throw an error though.

That error means an event was fired but none were found in the linked list.

It would be very helpful if you could reproduce this consistently. You can use `VS.EventQueue.Dump()` to see all queued events at any time.

**Comment by gsBASE** [comment]
Interesting. It looks like after this error occurs, the entire event queue is empty, despite there not being any code in my script that calls `VS.EventQueue.Clear()` to clear it.

Upon calling `VS.EventQueue.Dump()`, I get the following in the console:
```
VS::EventQueue::Dump: 138.233 : next(-1), last(133.7)
VS::EventQueue::Dump: end.
```

Also, as I should have probably clarified in the original post, I'm running on Portal 2 and not CS:GO.

**Comment by gsBASE** [comment]
Upon further investigation, I realized that I'm adding events within the event function:
```squirrel
function Phase2Attack(fTotalAttackTime)
{
	local fWarmupTime = fTotalAttackTime * 0.5;		// 50% of the attack time will be a warmup.
	local fCooldownTime = fWarmupTime + 0.35;
	
	// Pick our attack areas.
	aSelected = c_Core.SelectAttackSectors(3);
	
	VS.EventQueue.AddEvent( Phase2Warmup, 0, [this, aSelected] );
	VS.EventQueue.AddEvent( Phase2PerformAttack, fWarmupTime, [this, aSelected] );
	VS.EventQueue.AddEvent( Phase2Cooldown, fCooldownTime, [this, aSelected] );
}
```

Is it possible that this is causing the crash?

**Comment by samisalreadytaken** [comment]
The reason might be that the server tick interval is assumed to be 64 for CSGO.

Could you try with `sv_alternateticks 0` and see if it happens on that? Portal 2 tickrate without alternate ticks is 60, which is close enough to 64.

Could you also separately try putting `0.0001` instead of `0` in delay values on `AddEvent` calls inside event funcs? `0` executes the queued event immediately after the current one finishes, putting _some_ delay makes it execute on the next tick.

**Comment by gsBASE** [comment]
Thank you! It looks like using `FrameTime()` has consistently fixed it!
